import photo_speaker_1 from '../assets/event/speakers/speaker_1.png';
import photo_speaker_2 from '../assets/event/speakers/speaker_2.png';
import photo_speaker_3 from '../assets/event/speakers/speaker_3.png';

export const mockUserData = {
  id: 1,
  firstName: 'Екатерина',
  lastName: 'Краснова',
  email: 'example@yandex.ru',
  phoneNumber: '9162323232',
  interest: 'Frontend',
  notificationByTelegram: false,
  notificationByWhatsapp: true,
  notificationByVk: false,
  notificationByViber: false,
  telegram: '',
  whatsapp: 'dwadwa',
  vk: '',
  viber: 'dsadsa',
};

export const mockQuestionData = [
  {
    question: 'Какое мероприятие вы проводите?',
    answer:
      'Мы проводим IT конференцию под названием "Восхитительное объяснение возможностей JS", где ведущие эксперты рассказывают о последних технологических тенденциях и инновациях.',
  },
  {
    question: 'Где и когда пройдет ваше мероприятие?',
    answer:
      'Мероприятия пройдет 3 сентября в 12:00, по адрусу г. Владивосток, ул. Брэндана Эйха, д. 404. Так же меропритяие можно будет посмотреть онлайн на нашем сайте',
  },
  {
    question: 'Как можно зарегистрироваться на участие в мероприятии?',
    answer:
      'Нажмите кнопку "Зарегистрироваться" ниже. После регистрации вы получите подтверждение участия и дальнейшие инструкции о подключении к онлайн трансляции.',
  },
];

export const mockSpeakerData = [
  {
    id: 1,
    firstName: 'Алиса',
    lastName: 'Калакимова',
    position: 'Руководитель группы тестирования',
    about: 'Вошла в IT в 2010 году. Работала в e-commerce',
    photo: photo_speaker_1,
  },
  {
    id: 2,
    firstName: 'Андрей',
    lastName: 'Калакимов',
    position: 'Разработчик джава',
    about: 'C 2005 года работаю в Яндексе: начинал как разработчик',
    photo: photo_speaker_2,
  },
  {
    id: 3,
    firstName: 'Эксперт Роберт',
    lastName: 'Миронов',
    position: 'Бэкэнд',
    about: 'Бессменный ведущий подкаста Frontend Weekend и участник ПК FrontendConf',
    photo: photo_speaker_3,
  },
];

export const notifications = [
  {
    id: 1,
    title: 'Текст уведомления',
    text: 'Подробный текст уведомления',
    broadcastUrl: '/profile',
    age: '3 м',
  },
  {
    id: 2,
    title: 'Текст уведомления 2',
    text: 'Подробный текст уведомления 2',
    broadcastUrl: '/',
    age: '3 м',
  },
  {
    id: 3,
    title: 'Текст уведомления3',
    text: 'Подробный текст уведомления3',
    broadcastUrl: '/',
    age: '3 м',
  },
  {
    id: 4,
    title: 'Текст уведомления 4',
    text: 'Подробный текст уведомления 4',
    broadcastUrl: '/',
    age: '3 м',
  },
  {
    id: 5,
    title: 'Текст уведомления 5',
    text: 'Подробный текст уведомления 5',
    broadcastUrl: '/',
    age: '3 м',
  },
  {
    id: 6,
    title: 'Текст уведомления 6 ',
    text: 'Подробный текст уведомления 6',
    broadcastUrl: '/',
    age: '3 м',
  },
];

export const mockCardsData = [
  {
    id: 1,
    title: 'Восхитительное объяснение возможностей JS',
    speakerDescription: 'Эксперт Роберт Миронов Лид бэкенд - факультета',
    format: 'online+offline',
    status: 'upcoming',
    date: '12.07.2024',
    time: '15:33',
    city: 'Кемерово',
    address: 'ул. Пушкина, д.4, главный конференц-зал',
    seatsLeft: 0,
    colorTheme: 0,
  },
  {
    id: 2,
    title: 'Как стать крутым бэкенд-разработчиком? Ответы на ваши вопросы',
    speakerDescription: 'Бесплатный вебинар Эдриенн Таке',
    format: 'online',
    status: 'complete',
    date: '12.03.2024',
    time: '15:33',
    city: 'Москва',
    address: 'ул. Гагарина, д.4, главный конференц-зал',
    seatsLeft: 3,
    colorTheme: 1,
  },
  {
    id: 3,
    title: 'Практикум. Разработка Telegram-бота с использованием serverless',
    speakerDescription: 'Эксперт Анастасиялид фронтенд',
    format: 'online',
    status: 'live',
    date: '12.04.2024',
    time: '20:48',
    city: 'Воронеж',
    address: 'ул. Коминтеран, д.5, главный конференц-зал',
    seatsLeft: 123,
    colorTheme: 2,
  },
  {
    id: 4,
    title: 'Восхитительное объяснение возможностей JS',
    speakerDescription: 'Бесплатный вебинар Эдриенн Таке',
    format: 'online+offline',
    status: 'live',
    date: '15.08.2024',
    time: '10:48',
    city: 'Владивосток',
    address: 'ул. Гагарина, д.4, главный конференц-зал',
    seatsLeft: 33,
    colorTheme: 0,
  },
  {
    id: 5,
    title: 'ЯВеб Разработчик',
    speakerDescription: 'Эксперт Роберт Миронов Лид бэкенд - факультета.',
    format: 'online+offline',
    status: 'complete',
    date: '10.03.2024',
    time: '10:00',
    city: 'Санкт-Петербург',
    address: 'ул. Коминтеран, д.5, главный конференц-зал',
    seatsLeft: 18,
    colorTheme: 1,
  },
  {
    id: 6,
    title: 'Восхитительное объяснение возможностей JS',
    speakerDescription: 'Эксперт Роберт Миронов Лид бэкенд - факультета',
    format: 'online+offline',
    status: 'upcoming',
    date: '12.07.2024',
    time: '15:33',
    city: 'Кемерово',
    address: 'ул. Пушкина, д.4, главный конференц-зал',
    seatsLeft: 0,
    colorTheme: 0,
  },
  {
    id: 7,
    title: 'Как стать крутым бэкенд-разработчиком? Ответы на ваши вопросы',
    speakerDescription: 'Бесплатный вебинар Эдриенн Таке',
    format: 'online',
    status: 'complete',
    date: '12.03.2024',
    time: '15:33',
    city: 'Москва',
    address: 'ул. Гагарина, д.4, главный конференц-зал',
    seatsLeft: 3,
    colorTheme: 1,
  },
  {
    id: 8,
    title: 'Практикум. Разработка Telegram-бота с использованием serverless',
    speakerDescription: 'Эксперт Анастасиялид фронтенд',
    format: 'online',
    status: 'live',
    date: '12.04.2024',
    time: '20:48',
    city: 'Воронеж',
    address: 'ул. Коминтеран, д.5, главный конференц-зал',
    seatsLeft: 123,
    colorTheme: 2,
  },
  {
    id: 9,
    title: 'Восхитительное объяснение возможностей JS',
    speakerDescription: 'Бесплатный вебинар Эдриенн Таке',
    format: 'online+offline',
    status: 'upcoming',
    date: '15.08.2024',
    time: '10:48',
    city: 'Владивосток',
    address: 'ул. Гагарина, д.4, главный конференц-зал',
    seatsLeft: 33,
    colorTheme: 0,
  },
  {
    id: 10,
    title: 'ЯВеб Разработчик',
    speakerDescription: 'Эксперт Роберт Миронов Лид бэкенд - факультета.',
    format: 'online+offline',
    status: 'complete',
    date: '10.03.2024',
    time: '10:00',
    city: 'Санкт-Петербург',
    address: 'ул. Коминтеран, д.5, главный конференц-зал',
    seatsLeft: 18,
    colorTheme: 1,
  },
  {
    id: 11,
    title: 'Восхитительное объяснение возможностей JS',
    speakerDescription: 'Эксперт Роберт Миронов Лид бэкенд - факультета',
    format: 'online+offline',
    status: 'upcoming',
    date: '12.07.2024',
    time: '15:33',
    city: 'Кемерово',
    address: 'ул. Пушкина, д.4, главный конференц-зал',
    seatsLeft: 0,
    colorTheme: 0,
  },
  {
    id: 12,
    title: 'Как стать крутым бэкенд-разработчиком? Ответы на ваши вопросы',
    speakerDescription: 'Бесплатный вебинар Эдриенн Таке',
    format: 'online',
    status: 'complete',
    date: '12.03.2024',
    time: '15:33',
    city: 'Москва',
    address: 'ул. Гагарина, д.4, главный конференц-зал',
    seatsLeft: 3,
    colorTheme: 1,
  },
  {
    id: 13,
    title: 'Практикум. Разработка Telegram-бота с использованием serverless',
    speakerDescription: 'Эксперт Анастасиялид фронтенд',
    format: 'online',
    status: 'live',
    date: '12.04.2024',
    time: '20:48',
    city: 'Воронеж',
    address: 'ул. Коминтеран, д.5, главный конференц-зал',
    seatsLeft: 123,
    colorTheme: 2,
  },
  {
    id: 14,
    title: 'Восхитительное объяснение возможностей JS',
    speakerDescription: 'Бесплатный вебинар Эдриенн Таке',
    format: 'online+offline',
    status: 'upcoming',
    date: '15.08.2024',
    time: '10:48',
    city: 'Владивосток',
    address: 'ул. Гагарина, д.4, главный конференц-зал',
    seatsLeft: 33,
    colorTheme: 0,
  },
  {
    id: 15,
    title: 'ЯВеб Разработчик',
    speakerDescription: 'Эксперт Роберт Миронов Лид бэкенд - факультета.',
    format: 'online+offline',
    status: 'complete',
    date: '10.03.2024',
    time: '10:00',
    city: 'Санкт-Петербург',
    address: 'ул. Коминтеран, д.5, главный конференц-зал',
    seatsLeft: 18,
    colorTheme: 1,
  },
  {
    id: 16,
    title: 'Восхитительное объяснение возможностей JS',
    speakerDescription: 'Эксперт Роберт Миронов Лид бэкенд - факультета',
    format: 'online+offline',
    status: 'upcoming',
    date: '12.07.2024',
    time: '15:33',
    city: 'Кемерово',
    address: 'ул. Пушкина, д.4, главный конференц-зал',
    seatsLeft: 0,
    colorTheme: 0,
  },
  {
    id: 17,
    title: 'Как стать крутым бэкенд-разработчиком? Ответы на ваши вопросы',
    speakerDescription: 'Бесплатный вебинар Эдриенн Таке',
    format: 'online',
    status: 'complete',
    date: '12.03.2024',
    time: '15:33',
    city: 'Москва',
    address: 'ул. Гагарина, д.4, главный конференц-зал',
    seatsLeft: 3,
    colorTheme: 1,
  },
  {
    id: 18,
    title: 'Практикум. Разработка Telegram-бота с использованием serverless',
    speakerDescription: 'Эксперт Анастасиялид фронтенд',
    format: 'online',
    status: 'live',
    date: '12.04.2024',
    time: '20:48',
    city: 'Воронеж',
    address: 'ул. Коминтеран, д.5, главный конференц-зал',
    seatsLeft: 123,
    colorTheme: 2,
  },
  {
    id: 19,
    title: 'Восхитительное объяснение возможностей JS',
    speakerDescription: 'Бесплатный вебинар Эдриенн Таке',
    format: 'online+offline',
    status: 'upcoming',
    date: '15.08.2024',
    time: '10:48',
    city: 'Владивосток',
    address: 'ул. Гагарина, д.4, главный конференц-зал',
    seatsLeft: 33,
    colorTheme: 0,
  },
  {
    id: 20,
    title: 'ЯВеб Разработчик',
    speakerDescription: 'Эксперт Роберт Миронов Лид бэкенд - факультета.',
    format: 'online+offline',
    status: 'complete',
    date: '10.03.2024',
    time: '10:00',
    city: 'Санкт-Петербург',
    address: 'ул. Коминтеран, д.5, главный конференц-зал',
    seatsLeft: 18,
    colorTheme: 1,
  },
  {
    id: 21,
    title: 'Восхитительное объяснение возможностей JS',
    speakerDescription: 'Бесплатный вебинар Эдриенн Таке',
    format: 'online+offline',
    status: 'upcoming',
    date: '15.08.2024',
    time: '10:48',
    city: 'Владивосток',
    address: 'ул. Гагарина, д.4, главный конференц-зал',
    seatsLeft: 33,
    colorTheme: 0,
  },
  {
    id: 22,
    title: 'ЯВеб Разработчик',
    speakerDescription: 'Эксперт Роберт Миронов Лид бэкенд - факультета.',
    format: 'online+offline',
    status: 'complete',
    date: '10.03.2024',
    time: '10:00',
    city: 'Санкт-Петербург',
    address: 'ул. Коминтеран, д.5, главный конференц-зал',
    seatsLeft: 18,
    colorTheme: 1,
  },
];
